### PR TITLE
Add buttons to copy installation commands

### PR DESCRIPTION
**Pull request by malps13**
This PR is for adding buttons described in #26:

screenshot from 2015-01-01 20 51 40

Above is for desktop users (detected using lib from http://detectmobilebrowsers.com/)

Mobile users has commands wrapped in <input> tags which makes them easier to copy manualy.

### CODE REVIEW

**Comment by Nowaker** [comment]
> detected using lib from http://detectmobilebrowsers.com/

Isn't hidden-xs hidden-sm hidden-md just enough?

**Comment by malps13** [comment]
@Nowaker bootstrap responsive classes only consider device width. Script which I've referenced is rather checking user agent to make sure, that device is really not a mobile one. 

We could use bootstrap classes but then we have to accept the fact that for example desktop with browser not using fullscreen (for example taking only half of a screen) may return false positive and don't show copy button.

**Comment by malps13** [comment]
@Nowaker ping ;-)

**Comment by Nowaker** [comment]
Wording:

> ... simply open a terminal and execute

Otherwise, I'm fine.

**Pull request merged**
